<?php

/**
 * @file
 * Contains idix_publish.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_help().
 */
function idix_publish_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the idix_publish module.
    case 'help.page.idix_publish':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage content publication') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_node_delete().
 */
function publication_date_node_delete($node) {
  // Delete the publication date for the deleted node.
  \Drupal::database()->delete('publication_date')
    ->condition('nid', $node->nid)
    ->execute();
}

/**
 * @param EntityTypeInterface[] $entity_types
 */
function idix_publish_entity_type_build(&$entity_types) {
  if (isset($entity_types['node'])) {
    $entity_types['node']->setClass('Drupal\idix_publish\Entity\IdixNode');
  }
}
